"""
trpg.py
===========

이 모듈은 Discord 봇을 위한 자유도 기반 TRPG 시스템을 구현합니다.  
캐릭터 생성, 모험 시작, 자유 행동 판정 기능을 포함하며, 모든 캐릭터 정보와 진행 상태는 Supabase에 저장됩니다.  
주사위 굴림과 스탯 기반 판정은 시스템 규칙을 우선 적용하고, AI(Gemini)는 상황 서술만 담당합니다.  

명령어 구조
------------

모든 TRPG 관련 슬래시 명령어는 `/trpg` 하위 명령어 형태로 제공됩니다.

- `/trpg 캐릭터생성` – 캐릭터를 생성합니다. 스탯 합계가 100을 넘지 않도록 제한합니다.  
- `/trpg 모험시작` – AI 게임마스터(GM)가 현재 상황을 설명하며 모험을 시작합니다.  
- `/trpg 행동 (내용)` – 자유롭게 행동을 입력하여 판정과 결과를 진행합니다.  

Supabase 테이블 구조 (SQL 예시)
-----------------------------

```sql
CREATE TABLE trpg_characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    guild_id TEXT NOT NULL,
    name TEXT,
    gender TEXT,
    job TEXT,
    stats JSONB,
    hp INTEGER,
    inventory JSONB,
    current_state TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now()),
    CONSTRAINT trpg_characters_user_guild_unique UNIQUE (user_id, guild_id)
);
```

각 레코드는 사용자와 길드에 대해 하나의 캐릭터를 나타냅니다. `current_state` 컬럼은 진행 중인 모험의 상황 설명을 저장하는 데 사용합니다.
"""

import os
import random
import time
import json
import asyncio
from typing import Optional, Dict, Tuple, List

import discord
from discord.ext import commands
from discord import app_commands

try:
    # Supabase 클라이언트 불러오기
    from supabase import create_client, Client
except ImportError:
    # supabase 패키지가 설치되어 있지 않으면 안내 메시지 출력
    def create_client(url: str, key: str):  # type: ignore
        raise ImportError(
            "Supabase 패키지가 설치되어 있지 않습니다. 'pip install supabase' 명령으로 설치하세요."
        )

# Gemini API 클라이언트
try:
    from google import genai
except ImportError:
    genai = None

# 환경 변수 로딩
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

supabase: Optional["Client"] = None
if SUPABASE_URL and SUPABASE_KEY:
    try:
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
    except Exception as e:
        print(f"❌ Supabase 클라이언트 생성 실패: {e}")
else:
    print("⚠️ Supabase 설정이 누락되었습니다. .env에 SUPABASE_URL 및 SUPABASE_KEY를 설정하세요.")

# Gemini 클라이언트 설정
gemini_client: Optional[genai.Client] = None
if genai and GEMINI_API_KEY:
    try:
        gemini_client = genai.Client(api_key=GEMINI_API_KEY)
    except Exception as e:
        print(f"❌ Gemini 클라이언트 초기화 실패: {e}")


########## 데이터베이스 헬퍼 함수 ##########

def get_character(user_id: int, guild_id: int) -> Optional[Dict[str, any]]:
    """사용자의 캐릭터를 Supabase에서 불러옵니다."""
    if not supabase:
        return None
    try:
        response = (
            supabase.table("trpg_characters")
            .select("*")
            .eq("user_id", str(user_id))
            .eq("guild_id", str(guild_id))
            .single()
            .execute()
        )
        data = getattr(response, "data", None)
        return data
    except Exception as e:
        print(f"❌ Supabase 캐릭터 조회 실패: {e}")
        return None


def upsert_character(
    user_id: int,
    guild_id: int,
    name: str,
    gender: str,
    job: str,
    stats: Dict[str, int],
    inventory: Optional[List[str]] = None,
    current_state: str = "",
) -> None:
    """캐릭터를 생성하거나 업데이트합니다. 동일한 user/guild 조합이면 덮어씁니다."""
    if not supabase:
        return
    inventory = inventory or []
    payload = {
        "user_id": str(user_id),
        "guild_id": str(guild_id),
        "name": name,
        "gender": gender,
        "job": job,
        "stats": stats,
        "hp": stats.get("HP", 10),
        "inventory": inventory,
        "current_state": current_state,
    }
    try:
        existing = (
            supabase.table("trpg_characters")
            .select("id")
            .eq("user_id", str(user_id))
            .eq("guild_id", str(guild_id))
            .execute()
        )
        existing_data = getattr(existing, "data", [])
        if existing_data:
            supabase.table("trpg_characters").update(payload).eq("user_id", str(user_id)).eq("guild_id", str(guild_id)).execute()
        else:
            supabase.table("trpg_characters").insert(payload).execute()
    except Exception as e:
        print(f"❌ Supabase 캐릭터 upsert 실패: {e}")


def update_character_hp(user_id: int, guild_id: int, new_hp: int) -> None:
    """캐릭터 HP를 업데이트합니다."""
    if not supabase:
        return
    try:
        supabase.table("trpg_characters").update({"hp": new_hp}).eq("user_id", str(user_id)).eq("guild_id", str(guild_id)).execute()
    except Exception as e:
        print(f"❌ Supabase HP 업데이트 실패: {e}")


def update_character_state(user_id: int, guild_id: int, new_state: str) -> None:
    """캐릭터의 현재 상황 상태를 업데이트합니다."""
    if not supabase:
        return
    try:
        supabase.table("trpg_characters").update({"current_state": new_state}).eq("user_id", str(user_id)).eq("guild_id", str(guild_id)).execute()
    except Exception as e:
        print(f"❌ Supabase 상태 업데이트 실패: {e}")


########## 게임 로직 함수 ##########

def is_action_allowed(action: str) -> bool:
    """허용되지 않는 키워드가 포함되어 있는지 확인합니다."""
    banned_keywords = [
        "신이 된다",
        "모든",
        "즉사",
        "죽인다",
        "모두 죽",
        "전부 죽",
        "무적",
        "불멸",
        "무한",
    ]
    lowered = action.lower().replace(" ", "")
    for word in banned_keywords:
        if word.replace(" ", "") in lowered:
            return False
    return True


def classify_action(action: str) -> Tuple[str, int]:
    """행동 문자열을 분석하여 사용할 스탯과 난이도를 결정합니다.

    반환값: (stat_key, difficulty)
    stat_key는 "STR", "DEX", "INT", "CHA" 중 하나이며, 인식하지 못하면 "INT"를 기본값으로 사용합니다.
    difficulty는 10~18 사이의 난수를 기본으로 하되, 키워드에 따라 조정할 수 있습니다.
    """
    stat_key = "INT"
    difficulty = random.randint(10, 18)
    text = action.lower()
    if any(kw in text for kw in ["유혹", "매혹", "설득", "친해지", "미인"]):
        stat_key = "CHA"
        difficulty = random.randint(8, 16)
    elif any(kw in text for kw in ["공격", "부수", "때리", "베기", "찌르"]):
        stat_key = "STR"
        difficulty = random.randint(10, 18)
    elif any(kw in text for kw in ["은신", "몰래", "도둑", "숨", "피하", "회피"]):
        stat_key = "DEX"
        difficulty = random.randint(10, 18)
    elif any(kw in text for kw in ["분석", "조사", "연구", "지식", "파악"]):
        stat_key = "INT"
        difficulty = random.randint(10, 18)
    else:
        stat_key = "INT"
        difficulty = random.randint(12, 20)
    return stat_key, difficulty


def roll_dice(stat_value: int) -> Tuple[int, int, str]:
    """1d20 주사위를 굴려 스탯을 더해 결과를 도출합니다.

    반환값: (natural_roll, total, outcome)
    outcome은 "critical_success", "success", "failure", "critical_failure" 중 하나입니다.
    """
    natural = random.randint(1, 20)
    total = natural + stat_value
    if natural == 20:
        return natural, total, "critical_success"
    if natural == 1:
        return natural, total, "critical_failure"
    return natural, total, "pending"


########## Discord Cog 정의 ##########

class TRPGCog(commands.Cog):
    """자유도 기반 TRPG 시스템을 제공하는 Cog. 모든 명령은 /trpg 그룹 하위로 제공됩니다."""

    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.trpg_group = app_commands.Group(name="trpg", description="TRPG 시스템 명령어 모음")

        @self.trpg_group.command(name="캐릭터생성", description="새로운 TRPG 캐릭터를 생성합니다. 스탯 총합은 100을 초과할 수 없습니다.")
        @app_commands.describe(
            이름="캐릭터 이름",
            성별="성별 (예: 남성, 여성, 기타)",
            직업="직업 (예: 전사, 도적, 마법사 등)",
            힘="힘(STR) 스탯 (0~100)",
            민첩="민첩(DEX) 스탯 (0~100)",
            지능="지능(INT) 스탯 (0~100)",
            체력="체력(HP) 스탯 (0~100)",
            매력="매력(CHA) 스탯 (0~100)",
        )
        async def create_character_cmd(
            interaction: discord.Interaction,
            이름: str,
            성별: str,
            직업: str,
            힘: Optional[int] = None,
            민첩: Optional[int] = None,
            지능: Optional[int] = None,
            체력: Optional[int] = None,
            매력: Optional[int] = None,
        ) -> None:
            user_id = interaction.user.id
            guild_id = interaction.guild.id if interaction.guild else 0
            provided_stats = {
                "STR": 힘 if 힘 is not None else None,
                "DEX": 민첩 if 민첩 is not None else None,
                "INT": 지능 if 지능 is not None else None,
                "HP": 체력 if 체력 is not None else None,
                "CHA": 매력 if 매력 is not None else None,
            }
            total = sum(v for v in provided_stats.values() if v is not None)
            if total > 100:
                await interaction.response.send_message(
                    f"❌ 스탯 총합이 100을 초과했습니다. 현재 합계: {total}",
                    ephemeral=True,
                )
                return
            remaining_points = 100 - total
            missing_keys = [k for k, v in provided_stats.items() if v is None]
            stats = provided_stats.copy()
            for i, key in enumerate(missing_keys):
                if i == len(missing_keys) - 1:
                    stats[key] = remaining_points
                else:
                    val = random.randint(0, remaining_points)
                    stats[key] = val
                    remaining_points -= val
            if remaining_points > 0 and missing_keys:
                stats[missing_keys[0]] += remaining_points
            # Supabase 저장
            upsert_character(user_id, guild_id, 이름, 성별, 직업, stats, [], "")
            embed = discord.Embed(title="캐릭터 생성", color=discord.Color.blue())
            embed.add_field(name="이름", value=이름, inline=False)
            embed.add_field(name="성별", value=성별, inline=False)
            embed.add_field(name="직업", value=직업, inline=False)
            embed.add_field(
                name="스탯",
                value=f"STR: {stats['STR']}, DEX: {stats['DEX']}, INT: {stats['INT']}, HP: {stats['HP']}, CHA: {stats['CHA']}",
                inline=False,
            )
            embed.set_footer(text="모험을 시작하려면 /trpg 모험시작 을 사용하세요.")
            await interaction.response.send_message(embed=embed)

        @self.trpg_group.command(name="모험시작", description="AI 게임마스터가 모험을 시작하고 현재 상황을 설명합니다.")
        async def start_adventure_cmd(interaction: discord.Interaction) -> None:
            user_id = interaction.user.id
            guild_id = interaction.guild.id if interaction.guild else 0
            character = get_character(user_id, guild_id)
            if character is None:
                await interaction.response.send_message(
                    "❌ 먼저 /trpg 캐릭터생성 명령으로 캐릭터를 생성하세요!",
                    ephemeral=True,
                )
                return
            narrative = ""
            if gemini_client:
                try:
                    prompt = (
                        "TRPG 게임마스터로서 캐릭터의 모험을 시작하세요. 현실적인 세계관을 배경으로 하고, "
                        "캐릭터에게 현재 상황과 주변 환경을 한글로 묘사하세요. 캐릭터 이름과 직업, 스탯 정보를 참고하여 "
                        "이야기를 시작하세요. 긴 설명은 피하고, 다음 행동을 유도하는 간단한 상황 설명을 작성하세요."
                        f"\n\n캐릭터 정보: 이름={character['name']}, 직업={character['job']}, 성별={character['gender']}, "
                        f"스탯={{STR:{character['stats']['STR']}, DEX:{character['stats']['DEX']}, INT:{character['stats']['INT']}, HP:{character['hp']}, CHA:{character['stats']['CHA']}}}"
                    )
                    resp = gemini_client.models.generate_content(
                        model="models/gemini-2.5-flash-lite", contents=prompt
                    )
                    narrative = resp.text if hasattr(resp, "text") else ""
                except Exception as e:
                    print(f"⚠️ Gemini 초기 상황 생성 실패: {e}")
            if not narrative:
                narrative = "어두운 숲에서 모험이 시작됩니다. 당신은 주변을 둘러보며 다음 행동을 고민합니다."
            update_character_state(user_id, guild_id, narrative)
            embed = discord.Embed(title="모험 시작", description=narrative, color=discord.Color.green())
            embed.set_footer(text="행동을 하려면 /trpg 행동 <내용> 을 입력하세요.")
            await interaction.response.send_message(embed=embed)

        @self.trpg_group.command(name="행동", description="TRPG 자유 행동을 수행합니다.")
        @app_commands.describe(
            내용="자유롭게 입력하는 행동 내용 (예: 상인을 설득한다, 문을 부순다 등)"
        )
        async def perform_action_cmd(interaction: discord.Interaction, 내용: str) -> None:
            user_id = interaction.user.id
            guild_id = interaction.guild.id if interaction.guild else 0
            character = get_character(user_id, guild_id)
            if character is None:
                await interaction.response.send_message(
                    "❌ 먼저 /trpg 캐릭터생성 명령으로 캐릭터를 생성하세요!",
                    ephemeral=True,
                )
                return
            current_state = character.get("current_state") or ""
            if not current_state:
                await interaction.response.send_message(
                    "❌ 모험을 시작하지 않았습니다. 먼저 /trpg 모험시작 명령을 사용하세요!",
                    ephemeral=True,
                )
                return
            if not is_action_allowed(내용):
                await interaction.response.send_message(
                    "❌ 해당 행동은 시스템 규칙에 의해 허용되지 않습니다. 다른 행동을 시도해 주세요.",
                    ephemeral=True,
                )
                return
            stat_key, difficulty = classify_action(내용)
            stat_value = int(character["stats"].get(stat_key, 0))
            natural, total, outcome = roll_dice(stat_value)
            if outcome == "pending":
                outcome = "success" if total >= difficulty else "failure"
            hp_change = 0
            if stat_key == "STR" and outcome in ("failure", "critical_failure"):
                hp_change = -random.randint(1, 5)
                new_hp = max(0, int(character["hp"]) + hp_change)
                update_character_hp(user_id, guild_id, new_hp)
            narrative = ""
            if gemini_client:
                try:
                    prompt = (
                        "당신은 TRPG 게임마스터입니다. 이전 상황과 캐릭터의 자유 행동 및 주사위 판정을 참고해 다음 상황을 묘사하세요. "
                        "항상 게임 규칙을 우선 적용하고, 결과에 따라 성공/실패를 반영하세요. 지나치게 과장하거나 규칙을 무시하지 마세요. "
                        "한글로 간결하게 설명하세요.\n\n"
                        f"이전 상황: {current_state}\n"
                        f"캐릭터 정보: 이름={character['name']}, 직업={character['job']}, 성별={character['gender']}, "
                        f"스탯={{STR:{character['stats']['STR']}, DEX:{character['stats']['DEX']}, INT:{character['stats']['INT']}, HP:{character['hp']}, CHA:{character['stats']['CHA']}}}\n"
                        f"행동: {내용}\n"
                        f"판정: stat={stat_key}, 주사위={natural}, 스탯값={stat_value}, 총합={total}, 난이도={difficulty}, 결과={outcome}\n"
                        "결과에 어울리는 상황 묘사를 이어가고, 다음 행동을 유도하는 짧은 설명을 작성하세요."
                    )
                    resp = gemini_client.models.generate_content(
                        model="models/gemini-2.5-flash-lite", contents=prompt
                    )
                    narrative = resp.text if hasattr(resp, "text") else ""
                except Exception as e:
                    print(f"⚠️ Gemini 상황 생성 실패: {e}")
            if not narrative:
                narrative = "모험이 계속됩니다."
            update_character_state(user_id, guild_id, narrative)
            embed = discord.Embed(title="행동 결과", color=discord.Color.purple())
            embed.add_field(name="행동", value=내용, inline=False)
            embed.add_field(name="사용 스탯", value=stat_key, inline=True)
            embed.add_field(name="스탯 값", value=str(stat_value), inline=True)
            embed.add_field(name="주사위 (1d20)", value=str(natural), inline=True)
            embed.add_field(name="총합", value=str(total), inline=True)
            embed.add_field(name="난이도", value=str(difficulty), inline=True)
            result_text = {
                "critical_success": "대성공!",
                "success": "성공",
                "failure": "실패",
                "critical_failure": "대실패",
            }[outcome]
            embed.add_field(name="결과", value=result_text, inline=False)
            if hp_change < 0:
                embed.add_field(name="HP 감소", value=f"{abs(hp_change)} 감소", inline=False)
            embed.add_field(name="새로운 상황", value=narrative[:1024], inline=False)
            await interaction.response.send_message(embed=embed)

    @commands.Cog.listener()
    async def on_ready(self):
        # Cog 로드 시 /trpg 그룹을 명령 트리에 등록합니다. on_ready에서 중복 등록을 피하기 위해 한번만 실행합니다.
        try:
            self.bot.tree.add_command(self.trpg_group)
            print("✅ TRPG 명령어 그룹 등록 완료!")
        except Exception as e:
            print(f"⚠️ TRPG 명령어 그룹 등록 실패 또는 이미 등록됨: {e}")


async def setup(bot: commands.Bot) -> None:
    """Cog를 비동기로 등록합니다."""
    cog = TRPGCog(bot)
    await bot.add_cog(cog)
